baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Rushed Robin'
theme = 'archie'
googleAnalytics = "G-YC0GT79X8J"

paginate=5 # articles per page

# Code Highlight
pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = ""
	favicon = "/favicon.png"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/colms"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
